// generated by static-shard@0.0.0 — do not edit
export interface Movies {
  id: string;
  title: string;
  year: number;
  rating: number;
  director: string;
  genres: string[];
  overview: string;
}

export interface Records {
  movies: Movies;
}

export const schema = {
  movies: {
    fields: {
      title: { kind: "string", operators: ["equals", "in", "startsWith", "contains", "not"] },
      year: { kind: "number", operators: ["equals", "in", "gt", "gte", "lt", "lte", "not"] },
      rating: { kind: "number", operators: ["equals", "in", "not"] },
      director: { kind: "string", operators: ["equals", "in", "startsWith", "not"] },
      genres: { kind: "string", operators: ["equals", "in", "startsWith", "not"], multi: true },
    },
  },
} as const;

export type Schema = typeof schema;
