import type { Manifest } from "./types.js";

function pascalCase(name: string): string {
  return name.length === 0 ? name : name[0]!.toUpperCase() + name.slice(1);
}

function tsTypeForKind(kind: string): string {
  switch (kind) {
    case "number":
      return "number";
    case "boolean":
      return "boolean";
    case "string":
    case "date":
      return "string";
    default:
      return "unknown";
  }
}

function generatedHeader(generatorVersion: string): string {
  return `// generated by static-shard@${generatorVersion} — do not edit`;
}

export function generateSchemaTs(manifest: Manifest, generatorVersion: string): string {
  const { collection, fields } = manifest.schema;
  const typeName = pascalCase(collection);
  const fieldEntries = Object.entries(fields);

  const interfaceLines = fieldEntries.map(([name, field]) => `  ${name}: ${tsTypeForKind(field.kind)};`).join("\n");

  const indexedFieldLines = fieldEntries
    .filter(([, field]) => field.indexed)
    .map(([name, field]) => {
      const operators = field.operators.map((op) => `"${op}"`).join(", ");
      return `      ${name}: { kind: "${field.kind}", operators: [${operators}] },`;
    })
    .join("\n");

  return `${generatedHeader(generatorVersion)}
export interface ${typeName} {
${interfaceLines}
}

export interface Records {
  ${collection}: ${typeName};
}

export const schema = {
  ${collection}: {
    fields: {
${indexedFieldLines}
    },
  },
} as const;

export type Schema = typeof schema;
`;
}

export function generateClientTs(manifest: Manifest, opts: { basePath: string; generatorVersion: string }): string {
  const { collection } = manifest.schema;

  return `${generatedHeader(opts.generatorVersion)}
import { createClient, type Collection, type ClientOptions, type GenericClient } from "static-shard";
import { schema, type Schema, type Records } from "./schema.js";

export interface Db {
  ${collection}: Collection<Schema["${collection}"], Records["${collection}"]>;
}

const DEFAULT_BASE_PATH = ${JSON.stringify(opts.basePath)};

export function connect(opts?: Partial<ClientOptions>): Db {
  const generic: GenericClient<Schema, Records> = createClient<Schema, Records>(schema, {
    basePath: DEFAULT_BASE_PATH,
    ...opts,
  });
  return generic as unknown as Db;
}
`;
}
