import { describe, expect, test } from "vitest";
import { generateSchemaTs, generateClientTs } from "../src/codegen.js";
import type { Manifest } from "../src/types.js";

const manifest: Manifest = {
  formatVersion: 0,
  generatorVersion: "0.1.0",
  dataset: { collection: "movies", recordCount: 2, shardCount: 1, sortField: "year" },
  schema: {
    collection: "movies",
    sortField: "year",
    fields: {
      year: { kind: "number", isDate: false, indexed: true, operators: ["equals", "in", "gt", "gte", "lt", "lte"] },
      title: { kind: "string", isDate: false, indexed: false, operators: [] },
    },
  },
  shards: [{ hash: "abc123", bytes: 10, count: 2 }],
  zonemap: { year: { splitPoints: [2000, 2005] } },
};

describe("generateSchemaTs", () => {
  const output = generateSchemaTs(manifest, "0.1.0");

  test("carries the generated-header stamp", () => {
    expect(output).toContain("generated by static-shard@0.1.0 — do not edit");
  });

  test("full record interface includes every declared field, indexed or not", () => {
    expect(output).toContain("export interface Movies {");
    expect(output).toMatch(/year:\s*number;/);
    expect(output).toMatch(/title:\s*string;/);
  });

  test("the schema const's fields map includes ONLY indexed fields", () => {
    const schemaBlock = output.slice(output.indexOf("export const schema"));
    expect(schemaBlock).toContain('year: { kind: "number", operators: ["equals", "in", "gt", "gte", "lt", "lte"] }');
    expect(schemaBlock).not.toMatch(/\btitle:/);
  });

  test("maps the collection into Records", () => {
    expect(output).toContain("export interface Records {\n  movies: Movies;\n}");
  });
});

describe("generateSchemaTs — multi/absent (T7)", () => {
  const t7Manifest: Manifest = {
    ...manifest,
    schema: {
      ...manifest.schema,
      fields: {
        ...manifest.schema.fields,
        genres: { kind: "string", isDate: false, indexed: true, operators: ["equals", "in", "startsWith", "not"], multi: true },
        tagline: { kind: "string", isDate: false, indexed: true, operators: ["equals", "in", "startsWith", "not"], absent: true },
      },
    },
  };
  const output = generateSchemaTs(t7Manifest, "0.1.0");

  test("a multi field's record property is an array", () => {
    expect(output).toMatch(/genres:\s*string\[\];/);
  });

  test("an absent field's record property is optional", () => {
    expect(output).toMatch(/tagline\?:\s*string;/);
  });

  test("the schema const carries multi: true / absent: true only for the opted-in fields", () => {
    const schemaBlock = output.slice(output.indexOf("export const schema"));
    expect(schemaBlock).toContain("multi: true");
    expect(schemaBlock).toContain("absent: true");
    expect(schemaBlock).not.toMatch(/year:.*multi/);
    expect(schemaBlock).not.toMatch(/year:.*absent/);
  });
});

describe("generateSchemaTs — pk (T8)", () => {
  const pkManifest: Manifest = {
    ...manifest,
    schema: {
      ...manifest.schema,
      pk: "year",
      fields: { ...manifest.schema.fields, year: { ...manifest.schema.fields.year!, pk: true } },
    },
  };
  const output = generateSchemaTs(pkManifest, "0.1.0");

  test("the schema const carries a collection-level pk naming the field", () => {
    const schemaBlock = output.slice(output.indexOf("export const schema"));
    expect(schemaBlock).toMatch(/pk:\s*"year"/);
  });

  test("the pk field's own entry carries pk: true; other fields omit it", () => {
    const schemaBlock = output.slice(output.indexOf("export const schema"));
    expect(schemaBlock).toMatch(/year:\s*\{[^}]*pk:\s*true/);
  });

  test("no pk configured omits the collection-level pk key entirely", () => {
    const noPkOutput = generateSchemaTs(manifest, "0.1.0");
    const schemaBlock = noPkOutput.slice(noPkOutput.indexOf("export const schema"));
    expect(schemaBlock).not.toMatch(/\bpk:/);
  });
});

describe("generateClientTs", () => {
  const output = generateClientTs(manifest, { basePath: "/shard-data", generatorVersion: "0.1.0" });

  test("carries the generated-header stamp", () => {
    expect(output).toContain("generated by static-shard@0.1.0 — do not edit");
  });

  test("imports the generic runtime and the sibling schema module", () => {
    expect(output).toContain('from "static-shard"');
    expect(output).toContain('from "./schema.js"');
  });

  test("declares a named Db member for the collection", () => {
    expect(output).toContain("movies: Collection<Schema[\"movies\"], Records[\"movies\"]>");
  });

  test("bakes the configured basePath as connect()'s default", () => {
    expect(output).toContain('"/shard-data"');
    expect(output).toContain("export function connect(");
  });
});
